version: "3.9"

services:
  app:
    build: .
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ${GOOGLE_CREDENTIALS_JSON_PATH}:/tmp/keys/googlecredential.json:ro
    network_mode: host
  db:
    image: "mysql:8.0.27"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD : "${MYSQL_ROOT_PASSWORD}"
    volumes:
      - dbdata:/var/lib/mysql
    cap_add:
      - SYS_NICE
  seq:
    image: "datalust/seq"
    ports:
      - "5341:80"
    environment:
      ACCEPT_EULA : "y"
    volumes:
      - logdata:/data

volumes:
  dbdata:
  logdata:
