version: "3.9"

services:
  db:
    image: "mysql:8.0.27"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD : "SuperSecretPassword@123"
    volumes:
      - dbdata:/var/lib/mysql
  seq:
    image: "datalust/seq"
    ports:
      - "5341:80"
    environment:
      ACCEPT_EULA : "y"

volumes:
  dbdata:
